name: plantd
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  url_launcher: ^6.1.5
  intl: ^0.18.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  http: ^0.13.6
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:

    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"


